Видалив з css зайві властивості
Zyabrik10/project-team-11 pull request #38
Opened 2023-03-06 17:20 UTC by sgrischenko8

1) відцентрував секцію, обмежив ширину.

2) видалив властивості стилів кнопки, що співпадають із властивостями у common.css.

3) збільшив ширину кнопки у медіа-правила 1440рх

2023-03-06 17:36 UTC, Zyabrik10 requested changes

2023-03-06 17:36 UTC, Zyabrik10 commented on src/css/room/room-tour.css
>  }
треба не секції давати колір, а контейнеру

2023-03-06 18:52 UTC, sgrischenko8 commented on src/css/room/room-tour.css
>  }
в шляхах до img треба замінити такий формат ../../img/room/room-tour/room-collage2-mobile-w259@1x.jpg
на такий: ./img/room/room-tour/room-collage2-mobile-w259@1x.jpg   ?

2023-03-06 23:45 UTC, Zyabrik10 commented on src/css/room/room-tour.css
>  }
Так)

2023-03-07 08:04 UTC, sgrischenko8 commented on src/css/room/room-tour.css
>  }
змінив шлях до img

2023-03-07 10:09 UTC, Zyabrik10 approved these changes

2023-03-07 10:09 UTC, Zyabrik10 commented on src/css/room/room-tour.css
> +    max-width: none;
Думаю з max-width: none можуть бути проблеми

2023-03-07 10:10 UTC, merged